# Generated by Django 4.0.5 on 2022-06-21 11:51

from django.db import migrations, models
import news.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('date', models.DateTimeField(auto_now=True)),
                ('description', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to=news.models.image_folder)),
            ],
        ),
    ]
